#服务器信息配置
server:
  port: 12231

spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 10000

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/note?useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root

# mybatis plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml

# JWT配置
jwt:
  secret: ukc8BDbRigUDaY6pZFfWus2jZWLPHOOISOKSkmslmgdsSFSDSDGGSdsdglsdkgslkdngasdsdasgsjyttyj # 生产环境请更换为安全的密钥
  expiration: 3600000 # AccessToken过期时间（毫秒）
  refresh-expiration: 604800000 # RefreshToken过期时间（毫秒）
